### PR TITLE
added browser warn

### PR DESCRIPTION
**Pull request by zekth**
fixes: https://github.com/qmk/qmk_configurator/issues/148

2019-06-03 12_14_45-http___localhost_8080_#_1upkeyboards_1up60hse_LAYOUT_60_ansi - Internet Explorer

Note: is that normal that all content of the repo is using `CRLF` instead of `LF` ?

### CODE REVIEW

**Comment by yanfali** [comment]
@zekth looks good, though on Safari it's doing something weird an inserting extra Breaks. Now, we should be doing unix style CR only, now line feed. Where are you seeing that?

Screen Shot 2019-06-03 at 08 49 23

**Comment by yanfali** [comment]
Might be nice to make it dismissable with an X. Just the warning is enough

**Comment by zekth** [comment]
Maybe due to `a` tag? 

About CRLF it's using `yarn run lint`. Unix standard is `LF` not `CRLF`. btw

**Comment by yanfali** [comment]
@zekth yes, you are correct. Sorry, it shouldn't be, but I am on OSX. Maybe prettier settings need adjustment.

**Comment by yanfali** [comment]
@zekth are you using editorconfig? we have a defaults file

**Comment by yanfali** [comment]
I am seeing this when I run yarn lint
```
 yarn lint
yarn run v1.16.0
warning ../../package.json: No license field
$ vue-cli-service lint
 DONE  No lint errors found!
✨  Done in 7.25s.
```

**Comment by zekth** [comment]
issue is in `.editorconfig` missing line `end_of_line` for `[*]` or `[*.vue]`

**Comment by yanfali** [comment]
Awesome. Thanks.

**Pull request merged**
