### PR TITLE
[Colorway] GMK Aero

### PR DESCRIPTION
**Pull request by zekth**
see: 
2019-06-05 16_42_31-QMK Configurator

### CODE REVIEW

**Comment by yanfali** [comment]
Not sure what to do with this one, @mechmerlin any contacts over at zfrontier?

**Comment by zekth** [comment]
Staling. Closing it?

**Comment by yanfali** [comment]
> Staling. Closing it?

Find someone who owns the colorway to approve it and I can merge.

**Comment by zekth** [comment]
> > Staling. Closing it?
> 
> Find someone who owns the colorway to approve it and I can merge.

I don't

**Pull request closed without merging**
