### PR TITLE
Updated German translation

### PR DESCRIPTION
**Pull request by Vexatos**
Also matched the references in potato.js and switched to the metric system there.

I shortened a bunch of button names to make the buttons smaller, making them fit on the page better.

### CODE REVIEW

**Comment by Vexatos** [comment]
As a note, the i18n README should probably mention that the linter also has to be run on the lang files.

**Comment by yanfali** [comment]
Can you find something shorter for this one? 
```+        label: 'Auf Standard zurücksetzen',```
It makes the UI look kind of bad
Screen Shot 2019-10-03 at 09 08 39

**Comment by Vexatos** [comment]
I made it shorter.

**Comment by yanfali** [comment]
@heieisch how does seem to you?

**Comment by yanfali** [comment]
@kbravh @Vexatos please send a PR to update the instructions 😄 It'll count towards hacktober

**Comment by yanfali** [comment]
OK, getting close to accepting this one. Making one last effort to reach out to someone to verify translations.

**Comment by yanfali** [comment]
@kuchosauronad0 can you help out verifying

**Comment by heieisch** [comment]
That looks alright !

Best regards

Fabian Cnyrim

**Comment by yanfali** [comment]
we're removing hackoctoberfest labels because this will be done at the end of the event rather then per PR to prevent brigading and people trying to get points from just commenting

**Comment by shivam-51** [comment]
Is this issue still open ??

**Comment by smartjayansh** [comment]
Is this have hacktoberfest laber?

**Pull request merged**
