### PR TITLE
Zh Translations

### PR DESCRIPTION
**Pull request by mechmerlin**
Did this in traditional since thats what I'm most familiar with.

Translations are close, but I'm not too familiar with potato or tech terminologies. Hopefully this can be a good starting point for someone.

### CODE REVIEW

**Comment by kichloo** [comment]
Issue 1 on https://github.com/qmk/hacktoberfest fixed.

**Comment by yanfali** [comment]
@mechmerlin 
```$ prettier -c "./src/**/*.{js,vue,scss,css,json}"
Checking formatting...
src/i18n/zh/index.js
src/i18n/zh/print.js
src/i18n/zh/tester.js
Code style issues found in the above file(s). Forgot to run Prettier?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn run prettier:check" exited with 1.```

**Comment by crispgm** [comment]
@mechmerlin hi, what's going with this PR?

IMO, Chinese is like Portuguese, where there are some variations. And words used in keyboard are especially different.

I think we should split zh into zh-SC and zh-TC. And my zh-SC or zh-CN version has finished translation in my local machine. I will PR if this is solved.

**Comment by yanfali** [comment]
Aging this one out.

**Pull request closed without merging**
