### PR TITLE
Add GMK Keycap Set Colorways

### PR DESCRIPTION
**Pull request by mrsendyyk**
## GMK Keycap Set Colorways

* GMK Metropolis - Midnight ---- Designed by Nephlock
* GMK Handarbeit+ ---- Designed by Cocobrais
* GMK Olivia++ - Dark ---- Designed by Olivia
* GMK Dracula ---- Designed by pikku-allu
* GMK Phosphorous ---- Designed by Moridin

## Permission

- [x] GMK Metropolis - Midnight ---- [https://github.com/qmk/qmk_configurator/pull/823#issuecomment-699529459](https://github.com/qmk/qmk_configurator/pull/823#issuecomment-699529459)
- [x] GMK Handarbeit+ ---- [https://github.com/qmk/qmk_configurator/pull/828#issuecomment-710395450](https://github.com/qmk/qmk_configurator/pull/828#issuecomment-710395450)
- [x] GMK Olivia++ - Dark ---- [https://github.com/qmk/qmk_configurator/pull/828#issuecomment-705293471](https://github.com/qmk/qmk_configurator/pull/828#issuecomment-705293471)
- [x] GMK Dracula ---- [https://github.com/qmk/qmk_configurator/pull/828#issuecomment-705204294](https://github.com/qmk/qmk_configurator/pull/828#issuecomment-705204294)
- [x] GMK Phosphorous [https://github.com/qmk/qmk_configurator/pull/828#issuecomment-705204811](https://github.com/qmk/qmk_configurator/pull/828#issuecomment-705204811)

### CODE REVIEW

**Comment by mrsendyyk** [comment]
Permission for GMK Dracula

GMK-Dracula

**Comment by mrsendyyk** [comment]
Permission for GMK Phosphorous

GMK-Phosphorous

**Review by mrsendyyk — COMMENTED** [review]
Waiting permission for GMK Handarbeit+ and GMKOlivia++ - Dark.

**Comment by olivia** [comment]
Permission granted for Olivia++

**Comment by mrsendyyk** [comment]
> 
> 
> Permission granted for Olivia++

Thank you @olivia

**Comment by mrsendyyk** [comment]
Is there a way to keep `gmk-olivia-++-dark` or `gmk_olivia++_dark` and `gmk-handarbeit+` or `gmk_handarbeit+` without rename to `gmk-olivia-plus-plus-dark` or `gmk_olivia_plus_plus_dark` and `gmk-handarbeit-plus` or `gmk_handarbeit_plus` @noroadsleft? Because without rename it, i can't passed the prettier code style check.

**Review by mrsendyyk — COMMENTED** [review]
Waiting permission for GMK Handarbeit+.

**Review by mrsendyyk — COMMENTED** [review]
Deleted

**Comment by noroadsleft** [comment]
> Is there a way to keep `gmk-olivia-++-dark` or `gmk_olivia++_dark` and `gmk-handarbeit+` or `gmk_handarbeit+` without rename them to `gmk-olivia-plus-plus-dark` or `gmk_olivia_plus_plus_dark` and `gmk-handarbeit-plus` or `gmk_handarbeit_plus` @noroadsleft? Because without rename them, i can't passed the prettier code style check.

Hey, sorry I've been absent here for so long. I had an issue with my development environment and lost nearly a week trying to fix it.

I don't know the answer here, but I'll look into it. I don't quite remember off-hand how the code handle the names of the colorways.

**Comment by mrsendyyk** [comment]
> 
> 
> @mrsendyyk Figured out the fix for your issue.
> 
> First, revert the last two commits to get the deleted files back:
> 
> ```
> git revert 7dcc3481b 8bc96bc0f
> ```
> 
> ... then go to https://github.com/mrsendyyk/qmk_configurator/blob/7dcc3481b5663230095b1737c0db4e161b659cf3/src/components/Main.vue#L122
> 
> and change that one line to:
> 
> ```
>           .replace(/Ta/, 'TA')
>           .replace(/ ?Plus/g, '+');
> ```

Done @noroadsleft. So it makes the name still GMK Handarbeit+ and GMK Olivia++ - Dark right?

**Comment by noroadsleft** [comment]
> So that keeps the name still **GMK Handarbeit+** and **GMK Olivia++ - Dark** right?

Yep:

image

**Review by noroadsleft — COMMENTED** [review]
Still waiting on GMK Handarbeit+ permissions, but looks good otherwise.

**Comment by yanfali** [comment]
We should probably forbid this on principle. j/k. Looks good.

**Comment by mrsendyyk** [comment]
> 
> 
> We should probably forbid this on principle. j/k. Looks good.

I sent you a private message on Discord @yanfali.

**Comment by mrsendyyk** [comment]
Can we assume it as GMK Handarbeit+ permissions @noroadsleft @yanfali?

Screenshot_2020-10-17 Personal Messages Index(1)

**Review by noroadsleft — APPROVED** [review]
I'm not feeling great about GMK Phosphorous' contrast (again, medium grey :angry:), but I think I'd rather just get this in now and tweak it later. I have some work in the colorways along those lines I want to do anyway.

**Review by yanfali — APPROVED** [review]
`src/scss/colorways.scss` is getting a little big. Might be time to make it a folder with it's own `index.js`. Other than that this looks good to me.

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
