### PR TITLE
Update Japanese label to use endonym, reorder languages according to google's ordering

### PR DESCRIPTION
**Pull request by peepeetee**

### CODE REVIEW

**Review by fauxpark — APPROVED** [review]

**Comment by mtei** [comment]
Thank you for your PullRequest.

However, I don't think this needs to be changed. Because it is the result of intentionally selecting "Japanes".

see https://github.com/qmk/qmk_configurator/pull/543#discussion_r336758422

Tag: @shelaf

**Comment by fauxpark** [comment]
The general convention I see is for language selections to use their own spelling/character set.

The second point mentioned in that comment is nonsensical, pretty much any device which is able to use the Configurator effectively would have the basic CJK characters in at least one font.

**Comment by shelaf** [comment]
It's what I intended, but it's okay to change it as @fauxpark says. However, I think the display order should be changed. Currently in "value" order, but should be in "label" order.

**Comment by peepeetee** [comment]
> It's what I intended, but it's okay to change it as @fauxpark says. However, I think the display order should be changed. Currently in "value" order, but should be in "label" order.

I'm thinking of putting CJKV at the bottom and using alphabetic ordering for Latin/Cyrillic scripts, and stroke order for CJKV. 

Any better ideas?

Also, should I include the reordering in this PR, or open another PR for that?

**Comment by peepeetee** [comment]
My opinion is that sorting by language code is better than sorting by alphabetical/stroke order, as sorting by language code is unambiguous. 
If we are to sort alphabetical, it would introduce interesting dilemmas: should we sort Bahasa Malaysia under M or B? Русский under r, or put it at the end of the list? ~~we can also sort 日本語 under n for maximum confusion~~

**Comment by shelaf** [comment]
IMO, Unicode character code order is good to avoid the complexity.
cf. Google account language settings:
https://myaccount.google.com/language?continue=https%3A%2F%2Fmyaccount.google.com%2Fpersonal-info

The changes can be included in this PR.

**Comment by peepeetee** [comment]
> IMO, Unicode character code order is good to avoid the complexity. cf. Google account language settings: https://myaccount.google.com/language?continue=https%3A%2F%2Fmyaccount.google.com%2Fpersonal-info
> 
> The changes can be included in this PR.

Done

Anything else I should do before this PR could be merged?

**Review by noroadsleft — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks everyone!

**Pull request merged**
