### PR TITLE
Add keycode to title message

### PR DESCRIPTION
**Pull request by yanfali**
To help users learn the QMK key codes, add them to all keycode titles.

preview at https://yanfali.github.io/qmk_configurator

### CODE REVIEW

**Comment by mechmerlin** [comment]
LGTM =) 

Only qualm is that in Application and Multimedia keys, we have KC_VOLD and KC_VOLUP in both lists, I think we can take it out of one of them.

**Comment by yanfali** [comment]
@mechmerlin consolidated media keys

**Comment by yanfali** [comment]
@skullydazed @jackhumbert this one should be good to go

**Comment by jackhumbert** [comment]
Nice - thanks :)

**Pull request merged**
