### PR TITLE
[converter/a1200] Match layout name

### PR DESCRIPTION
**Pull request by 8bits4ever**
QMK Configurator currently not working for this keyboard. Trying to fix it

-Change layout name to match the one from info.json file
-Created a .json file for each variant of the keyboard.

Not sure if Im doing it right though. Please check.

Thanks!

### CODE REVIEW

**Review by noroadsleft — CHANGES_REQUESTED** [review]
This won't work.

The name you use here: https://github.com/qmk/qmk_firmware/blob/a4aa6ccf7b98a203c16be51e8db4970a80f0abfd/keyboards/converter/a1200/info.json#L7 ...
must match the name used here: https://github.com/qmk/qmk_firmware/blob/a4aa6ccf7b98a203c16be51e8db4970a80f0abfd/keyboards/converter/a1200/a1200.h#L28

First change the layout macro reference in your `info.json` file to `LAYOUT`, then we can come back to this.

**Review by noroadsleft — CHANGES_REQUESTED** [review]
Item 2 of 2: correct the filenames (both have an extra underscore):

```
git mv public/keymaps/c/converter_a1200__miss1200_default.json public/keymaps/c/converter_a1200_miss1200_default.json
git mv public/keymaps/c/converter_a1200__teensy2pp_default.json public/keymaps/c/converter_a1200_teensy2pp_default.json
```

**Comment by 8bits4ever** [comment]
Ok, done!

**Review by noroadsleft — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
