### PR TITLE
Added Italian translation

### PR DESCRIPTION
**Pull request by michizhou**
I just created the Italian (it) translation folder and added all the necessary translations. Suggestions for any potential improvements to the documentation are welcome.

### CODE REVIEW

**Comment by gargarchit** [comment]
Nice addition @michizhou

**Comment by yanfali** [comment]
@michizhou are you a native Italian speaker or is this Google translate?

**Comment by michizhou** [comment]
I studied Italian for two years in college (just a few years ago). This isn't Google Translate.

**Comment by yanfali** [comment]
Here's some feedback from someone I know who lived in Italy for about a decade:

Screen Shot 2019-10-28 at 12 30 35

**Comment by federikovi** [comment]
Ciao! 👋 
I am an Italian native speaker and I wanted to translate the documentation, I've seen there's already work done in this PR but I can't find the `it` folder in the docs. Has it been deleted?

**Comment by federikovi** [comment]
@yanfali Great, thank you

**Pull request merged**
