### PR TITLE
Fixed bug with spinner where text was appearing gray.

### PR DESCRIPTION
**Pull request by KartikSoneji**
Fixed .spinner css class so that the child classes (.message and .status) would actually have the style applied to them.

## Before
image

## After
image

### CODE REVIEW

**Comment by yanfali** [comment]
I think this one crept in because of the dark mode. Can you test whether the & is still needed?

**Comment by KartikSoneji** [comment]
OK, just checked, the `&` is not required.

**Comment by noroadsleft** [comment]
Thanks for this! I noticed it a while back but hadn't had time to track it down, and it was bothering me quite a bit.

**Comment by KartikSoneji** [comment]
You are welcome.

**Pull request merged**
