### PR TITLE
Add GHS.RAR default keymap

### PR DESCRIPTION
**Pull request by ramonimbao**
Add the default GHS.RAR keymap following https://github.com/qmk/qmk_firmware/pull/9561.

### CODE REVIEW

**Comment by noroadsleft** [comment]
I actually looked at the PR that added this keyboard to qmk_firmware earlier today, and I don't think the keymaps will work correctly on hardware, assuming the rest of the keyboard config is correct. None of the added keymaps includes a keycode for Right Shift, and all of the keymaps' layers end with commas.

**Comment by ramonimbao** [comment]
Oh that is worrisome. I'll look through my code again, and make the changes. Thanks for pointing that out!

**Comment by ramonimbao** [comment]
This got merged into master. I've also updated the commit hash.

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
