### PR TITLE
Improve logging in the application

### PR DESCRIPTION
**Pull request by zekth**
Moved the console.log to a proper logger to intercept everything the same way and have a factory. Currently it's using pino but, because we have a factory we can move to another dependency if needed. It outputs log like this:

Screenshot 2019-11-16 at 16 19 11

### CODE REVIEW

**Comment by zekth** [comment]
Edit: It's not working on bundled app. Working on this

**Comment by zekth** [comment]
I've done some improvement and i'm happy with it. Now it outputs like this:
Screenshot 2019-11-17 at 08 09 18

**Comment by yanfali** [comment]
let's try and get this merged tomorrow

**Comment by zekth** [comment]
Done :)

**Comment by zekth** [comment]
So seems like resolution of the stack and calling file in FF and Chrome are really different and this makes a bit a mess in the code. Do we still keep this logger feature but we delete the part to point the caller line? IMO i'd not mind as the logger is meant to be meaningfull with the infos in it and pointing the file is just an `extra feature`.

**Comment by yanfali** [comment]
> So seems like resolution of the stack and calling file in FF and Chrome are really different and this makes a bit a mess in the code. Do we still keep this logger feature but we delete the part to point the caller line? IMO i'd not mind as the logger is meant to be meaningfull with the infos in it and pointing the file is just an `extra feature`.

I disagree. We spend more time debugging code than writing it. I'm reluctant to lose a standard feature of the current console implementation.

**Comment by zekth** [comment]
> > So seems like resolution of the stack and calling file in FF and Chrome are really different and this makes a bit a mess in the code. Do we still keep this logger feature but we delete the part to point the caller line? IMO i'd not mind as the logger is meant to be meaningfull with the infos in it and pointing the file is just an `extra feature`.
> 
> I disagree. We spend more time debugging code than writing it. I'm reluctant to lose a standard feature of the current console implementation.

So a log formatter should be implemented.

**Comment by yanfali** [comment]
> > > So seems like resolution of the stack and calling file in FF and Chrome are really different and this makes a bit a mess in the code. Do we still keep this logger feature but we delete the part to point the caller line? IMO i'd not mind as the logger is meant to be meaningfull with the infos in it and pointing the file is just an `extra feature`.
> > 
> > 
> > I disagree. We spend more time debugging code than writing it. I'm reluctant to lose a standard feature of the current console implementation.
> 
> So a log formatter should be implemented.

It should work across FF and Chrome in a similar way. I personally don't do that much development on FF but we always support it, because it's good to have options and it prevents Chrome from becoming the next IE.

**Comment by zekth** [comment]
webpack resolution does not work the same way in FF and Chrome. In Chrome resolution is done if the path is prompted in the console, in the case of FF it's not. That's the blocking part.

**Comment by yanfali** [comment]
> webpack resolution does not work the same way in FF and Chrome. In Chrome resolution is done if the path is prompted in the console, in the case of FF it's not. That's the blocking part.

That sucks. I'm loathe to have a feature that only works on one browser.

**Comment by noroadsleft** [comment]
> That sucks. I'm loathe to have a feature that only works on one browser.

I'm undoubtedly biased, as Firefox is my main browser and has been almost exclusively since 2004, but hard agree. We support Chrome and Firefox officially, and both should be supported equally.

**Pull request merged**
