### PR TITLE
Addition of Nightwatch.js as a functional/integration test automation

### PR DESCRIPTION
**Pull request by WemansG90**
- Adds Nightwatch.js, a Node based test automation framework using webdriver/selenium
- Configured with profiles for headless chrome and headless firefox, which can run in parallel.
- Uses nightwatch-html-reporter for consolidated reports, versus the standard XML ones

Known issues:
- Screenshots on test failure/error seem to be broken, looks to be a Nightwatch issue
- NPM audit failures. Needs Nightwatch 1.0.X to release

### CODE REVIEW

**Comment by mechmerlin** [comment]
I am so happy you did this!! I've been reading up on nightwatch on my spare time and was mulling around on how to even get this up for QMK!

**Comment by yanfali** [comment]
Almost there, getting travis integration sorted out first. @WemansG90 do you have experience running nightwatch using travis? I'm trying to figure out how best to download all the binary deps

**Comment by WemansG90** [comment]
I've not used Travis before, but I can do some digging to figure it out. The browser binary path might have to get added to the config file, but I'll look it up.

**Comment by yanfali** [comment]
sorry @WemansG90 the travis-ci changes required some changes to the same files, you're going to need a rebase against the new master. My apologies.

**Comment by yanfali** [comment]
Thank you. Looks awesome.

**Pull request merged**
