### PR TITLE
[Keyboard]Add keyboard Naked48/60

### PR DESCRIPTION
**Pull request by Salicylic-acid3**
Add Naekd48/60 keyboard.

A 48/60 keys Ortholinear keyboard.
Salicylic-acid3

### CODE REVIEW

**Comment by Salicylic-acid3** [comment]
Where can I check the contents of compilation errors?
Naked60 uses tap dance in the default keymap to write 4 layers, but the configurator has 3 layers.
Is this a problem?

**Comment by noroadsleft** [comment]
> Where can I check the contents of compilation errors?

## naked48/rev1

Looks like the Naked48 fails because `RGBLED_NUM` is being defined only at keymap level in qmk_firmware, but Configurator can only use definitions from keyboard and revision level (`keyboards/naked48/`  or `keyboards/naked48/rev1/`, respectively). You might need to define the number used by the default keymap at the revision level, and then override it in each keymap's `config.h`.

<details>
<summary>Configurator Error Log</summary>

```
* Sending naked48/rev1:default_233a1e9 with LAYOUT
* Received job_id: 7afd61af-468d-4249-9141-4df7db7d9bbd
* Running . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
* Finished:
QMK Firmware 0.7.45
WARNING:
 Some git sub-modules are out of date or modified, please consider running:
 make git-submodule
 You can ignore this warning if you are not compiling any ChibiOS keyboards,
 or if you have modified the ChibiOS libraries yourself. 

Making naked48/rev1 with keymap default_233a1e9

avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/naked48/naked48.c                                                             In file included from quantum/quantum.h:40:0,
                 from keyboards/naked48/naked48.h:3,
                 from keyboards/naked48/naked48.c:1:
quantum/rgblight.h:142:21: error: ‘RGBLED_NUM’ undeclared here (not in a function)
 extern LED_TYPE led];
                     ^
 [ERRORS]  
 | 
 | 
 | 
tmk_core/rules.mk:377: recipe for target '.build/obj_naked48_rev1_default_233a1e9/keyboards/naked48/naked48.o' failed
make[1]: *** [.build/obj_naked48_rev1_default_233a1e9/keyboards/naked48/naked48.o] Error 1
Makefile:555: recipe for target 'naked48/rev1:default_233a1e9' failed
make: *** [naked48/rev1:default_233a1e9] Error 1
Make finished with errors
```
</details>

## naked60/rev1

This one I think is a Tap Dance error, which QMK Configurator doesn't support. Tap Dance is enabled at revision level, but the Configurator-generated keymap doesn't contain the necessary functions/definitions.



This is the `keymap.c` that QMK Configurator generates and attempts to compile for this build:

```c
#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_ENT, MO(3), KC_LCTL, KC_LALT, KC_LGUI, MO(1), KC_SPC, KC_SPC, MO(2), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT),
	[1] = LAYOUT(KC_ESC, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_DEL, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, KC_PIPE, KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, LSFT(KC_NUHS), LSFT(KC_NUBS), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MNXT, KC_VOLD, KC_VOLU, KC_MPLY),
	[2] = LAYOUT(KC_ESC, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TILD, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_DEL, KC_DEL, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_MINS, KC_EQL, KC_LBRC, KC_RBRC, KC_BSLS, KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_NUHS, KC_NUBS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[3] = LAYOUT(KC_ESC, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN1, KC_MS_U, KC_BTN2, KC_NO, LALT(KC_PSCR), KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_NO, KC_PSCR, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, LCA(KC_DEL), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RESET, RESET, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};
```

As you can see, it's just the include for the keyboard's header file (`QMK_KEYBOARD_H`) and the keymap itself – there's no extra features.

<details>
<summary>Configurator Error Log</summary>

```
* Sending naked60/rev1:default_f360c27 with LAYOUT
* Received job_id: a8dc505a-1707-422c-9781-4d2bc3bbc57e
* Queueing . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
* Running . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
* Finished:
QMK Firmware 0.7.45
WARNING:
 Some git sub-modules are out of date or modified, please consider running:
 make git-submodule
 You can ignore this warning if you are not compiling any ChibiOS keyboards,
 or if you have modified the ChibiOS libraries yourself. 

Making naked60/rev1 with keymap default_f360c27

avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/naked60/rev1/matrix.c                                                          [OK]      
Compiling: keyboards/naked60/rev1/split_util.c                                                      [OK]      
Compiling: keyboards/naked60/rev1/split_scomm.c                                                     [OK]      
Compiling: keyboards/naked60/naked60.c                                                              [OK]      
Compiling: keyboards/naked60/rev1/rev1.c                                                            [OK]      
Compiling: keyboards/naked60/keymaps/default_f360c27/keymap.c                                       [OK]      
Compiling: quantum/quantum.c                                                                        [OK]      
Compiling: quantum/keymap_common.c                                                                  [OK]      
Compiling: quantum/keycode_config.c                                                                 [OK]      
Compiling: quantum/debounce/sym_g.c                                                                 [OK]      
Compiling: quantum/process_keycode/process_tap_dance.c                                              [OK]      
Compiling: quantum/process_keycode/process_space_cadet.c                                            [OK]      
Compiling: keyboards/naked60/serial.c                                                               [OK]      
Archiving: .build/obj_naked60_rev1_default_f360c27/serial.o                                         [OK]      
Compiling: tmk_core/common/host.c                                                                   [OK]      
Compiling: tmk_core/common/keyboard.c                                                               [OK]      
Compiling: tmk_core/common/action.c                                                                 [OK]      
Compiling: tmk_core/common/action_tapping.c                                                         [OK]      
Compiling: tmk_core/common/action_macro.c                                                           [OK]      
Compiling: tmk_core/common/action_layer.c                                                           [OK]      
Compiling: tmk_core/common/action_util.c                                                            [OK]      
Compiling: tmk_core/common/print.c                                                                  [OK]      
Compiling: tmk_core/common/debug.c                                                                  [OK]      
Compiling: tmk_core/common/util.c                                                                   [OK]      
Compiling: tmk_core/common/eeconfig.c                                                               [OK]      
Compiling: tmk_core/common/report.c                                                                 [OK]      
Compiling: tmk_core/common/avr/suspend.c                                                            [OK]      
Compiling: tmk_core/common/avr/timer.c                                                              [OK]      
Compiling: tmk_core/common/avr/bootloader.c                                                         [OK]      
Assembling: tmk_core/common/avr/xprintf.S                                                           [OK]      
Compiling: tmk_core/common/magic.c                                                                  [OK]      
Compiling: tmk_core/common/mousekey.c                                                               [OK]      
Compiling: tmk_core/protocol/lufa/lufa.c                                                            [OK]      
Compiling: tmk_core/protocol/usb_descriptor.c                                                       [OK]      
Compiling: tmk_core/protocol/lufa/outputselect.c                                                    [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c                                       [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c                                        [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c                                [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c                                      [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c                                          [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c                                    [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c                                          [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c                                 [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c                                  [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c                                       [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c                                       [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Core/Events.c                                                  [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c                                         [OK]      
Compiling: lib/lufa/LUFA/Drivers/USB/Core/USBTask.c                                                 [OK]      
Linking: .build/naked60_rev1_default_f360c27.elf                                                    [ERRORS]  
 | 
 | .build/obj_naked60_rev1_default_f360c27/quantum/process_keycode/process_tap_dance.o: In function `process_tap_dance_action_on_reset':
 | /qmk_compiler/qmk_firmware/quantum/process_keycode/process_tap_dance.c:104: undefined reference to `tap_dance_actions'
 | /qmk_compiler/qmk_firmware/quantum/process_keycode/process_tap_dance.c:104: undefined reference to `tap_dance_actions'
 | /qmk_compiler/qmk_firmware/quantum/process_keycode/process_tap_dance.c:104: undefined reference to `tap_dance_actions'
 | /qmk_compiler/qmk_firmware/quantum/process_keycode/process_tap_dance.c:104: undefined reference to `tap_dance_actions'
 | /qmk_compiler/qmk_firmware/quantum/process_keycode/process_tap_dance.c:105: undefined reference to `tap_dance_actions'
 | .build/obj_naked60_rev1_default_f360c27/quantum/process_keycode/process_tap_dance.o:/qmk_compiler/qmk_firmware/quantum/process_keycode/process_tap_dance.c:105: more undefined references to `tap_dance_actions' follow
 | collect2: error: ld returned 1 exit status
 | 
tmk_core/rules.mk:298: recipe for target '.build/naked60_rev1_default_f360c27.elf' failed
make[1]: *** [.build/naked60_rev1_default_f360c27.elf] Error 1
Makefile:555: recipe for target 'naked60/rev1:default_f360c27' failed
make: *** [naked60/rev1:default_f360c27] Error 1
Make finished with errors
```
</details>

Pretty sure both of these will need changes on the qmk_firmware side before they work over here.

----

> Naked60 uses tap dance in the default keymap to write 4 layers, but the configurator has 3 layers.
> Is this a problem?

The layer mismatch isn't an issue for me considering it's because of Tap Dance. If we could work out similar or identical functionality on the qmk_firmware side without using Tap Dance, that would be ideal.

**Comment by yanfali** [comment]
unless you move tapdance to the keyboard level I don't think you'll get this working in configurator

**Comment by noroadsleft** [comment]
@yanfali The compilation issues were fixed in https://github.com/qmk/qmk_firmware/pull/7131. These keymaps are okay now. (Well, they were okay before, but the qmk_firmware was broken.)

@Salicylic-acid3 Be advised that I try to update these periodically, in an attempt to keep them 1:1 with the defaults on qmk_firmware.

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
