### PR TITLE
Move per key height and width calculations back into CSS

### PR DESCRIPTION
**Pull request by yanfali**
Take advantage of CSS Custom Variables and CSS calc to move height and width calculations into CSS where they really belong rather than per DOM key element.

 - ISO CSS contributed by @kbrock thanks so much for this work!

### Pros:
 - remove explicit height and width in each key style
 - reduces parsing load on the DOM
 - allows overriding through use of classes. Styles have highest specificity

### Cons:
 - pushes some work in the CSS parser
 - may be somewhat difficult to understand

### CODE REVIEW

**Comment by yanfali** [comment]
> 
> Is there any way we could get this to support arbitrary sizes?

We might be able to generate it from scss, it would require some parsing magic. @zekth any ideas? Tbh, all those keyboards are 1 offs and fixing them likely fixes things for a while. As for the rounding/typos errors, those should just be fixed.

**Comment by noroadsleft** [comment]
> As for the rounding/typos errors, those should just be fixed.

I failed to specify, but yes, that is my intention.

**Comment by yanfali** [comment]
@noroadsleft ready for review

**Comment by yanfali** [comment]
Screen Shot 2020-05-17 at 18 32 32
Screen Shot 2020-05-17 at 18 32 50
Screen Shot 2020-05-17 at 18 33 15
Screen Shot 2020-05-17 at 18 33 42
Screen Shot 2020-05-17 at 18 34 05

**Comment by noroadsleft** [comment]
Feature looks good, but is 909492cf89acf88260619f916fe9b5fc14fa6a41 meant to be on this branch?

**Comment by yanfali** [comment]
@noroadsleft good catch. fixed

**Comment by kbrock** [comment]
looks very good

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
