### PR TITLE
adjust json file to keymap.c file

### PR DESCRIPTION
**Pull request by greenjack-z**

### CODE REVIEW

**Comment by noroadsleft** [comment]
This doesn't match the default keymap that's currently on `qmk_firmware` repository - is that deliberate?

**Comment by greenjack-z** [comment]
> This doesn't match the default keymap that's currently on `qmk_firmware` repository - is that deliberate?

Yes, it if final at the moment and will stay as a default I believe. Anyway it's definitely better than it is now.

**Comment by noroadsleft** [comment]
> Yes, it if final at the moment and will stay as a default I believe. Anyway it's definitely better than it is now.

So is the plan that the default keymap on `qmk_firmware` is going to be updated to this?

**Comment by greenjack-z** [comment]
> So is the plan that the default keymap on `qmk_firmware` is going to be updated to this?
Yes, I will do it as a default.

**Review by noroadsleft — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
