### PR TITLE
PH translation index.js

### PR DESCRIPTION
**Pull request by Nievac**
PH translation [partial]

### CODE REVIEW

**Comment by yanfali** [comment]
@Nievac can you please follow the translation guide and run lint on your contribution? Many thanks.
@mechmerlin you want to check this?

**Comment by Nievac** [comment]
Okay I will @yanfali.

**Comment by mechmerlin** [comment]
Looks good to me!

**Comment by Nievac** [comment]
Hi @yanfali, I have PR #541 for tl-PH. Sorry for another PH translation.  At first I was confused about how will I make an efficient PR. Thank you, I am learning now how to use Git. I already run lint and it was okay.

**Comment by yanfali** [comment]
@Nievac close this one if the other one is better. thanks

**Pull request closed without merging**
