### PR TITLE
Adding language selection

### PR DESCRIPTION
**Pull request by zekth**
Adding language selection to the setting bar.

Also saving it to the localstorage

### CODE REVIEW

**Comment by zekth** [comment]
Nice find! Will fix it

**Comment by noroadsleft** [comment]
And now that that's done I'm thinking maybe it should save the setting to local storage on init. :man_facepalming: 

*noroadsleft is a bad code reviewer*

**Comment by zekth** [comment]
> And now that that's done I'm thinking maybe it should save the setting to local storage on init. 🤦‍♂
> 
> I don't know if that will lead to unintended consequences if the user's browser is in a language for which Configurator has no translation.
> 
> _noroadsleft is a bad code reviewer_

Why using an unused IO ? i think it's not necessary to do it on init.

**Comment by noroadsleft** [comment]
In that case, we call this done.

**Comment by yanfali** [comment]
@zekth  the dropdown doesn't update correctly when I switch language. Can you take a look?

Screen Shot 2019-09-30 at 09 56 59

Try switching from one language to another. The drop down remains in old language. You probably need to set the selected value.

**Comment by yanfali** [comment]
```Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
warning: Replace `>{{·$t('message.settingsPanel.fastInput.label')·}}</label` with `··>{{·$t('message.settingsPanel.fastInput.label')·}}</label⏎········` (prettier/prettier) at src/components/SettingsPanel.vue:11:9:
   9 |           @mouseover="help('fastInput')"
  10 |           class="settings-panel--text"
> 11 |         >{{ $t('message.settingsPanel.fastInput.label') }}</label>
     |         ^
  12 |       </div>
  13 |       <div>
  14 |         <toggle-button


warning: Replace `>{{·$t('message.settingsPanel.displaySizes.label')·}}</label` with `··>{{·$t('message.settingsPanel.displaySizes.label')·}}</label⏎········` (prettier/prettier) at src/components/SettingsPanel.vue:26:9:
  24 |           @mouseover="help('displaySizes')"
  25 |           :title="$t('message.settingsPanel.displaySizes.title')"
> 26 |         >{{ $t('message.settingsPanel.displaySizes.label') }}</label>
     |         ^
  27 |       </div>
  28 |       <div>
  29 |         <toggle-button


warning: Replace `>{{·$t('message.settingsPanel.toggleTutorial.label')·}}</label` with `··>{{·$t('message.settingsPanel.toggleTutorial.label')·}}</label⏎········` (prettier/prettier) at src/components/SettingsPanel.vue:41:9:
  39 |           @mouseover="help('displaySizes')"
  40 |           :title="$t('message.settingsPanel.toggleTutorial.title')"
> 41 |         >{{ $t('message.settingsPanel.toggleTutorial.label') }}</label>
     |         ^
  42 |       </div>
  43 |       <div>
  44 |         <toggle-button


warning: Replace `>{{·$t('message.settingsPanel.darkmode.title')·}}</label` with `··>{{·$t('message.settingsPanel.darkmode.title')·}}</label⏎········` (prettier/prettier) at src/components/SettingsPanel.vue:57:9:
  55 |           @mouseover="help('darkmode')"
  56 |           :title="$t('message.settingsPanel.darkmode.title')"
> 57 |         >{{ $t('message.settingsPanel.darkmode.title') }}</label>
     |         ^
  58 |       </div>
  59 |       <div>
  60 |         <toggle-button


warning: Replace `>{{·$t('message.settingsPanel.language.title')·}}</label` with `··>{{·$t('message.settingsPanel.language.title')·}}</label⏎········` (prettier/prettier) at src/components/SettingsPanel.vue:71:9:
  69 |           class="settings-panel--text"
  70 |           :title="$t('message.settingsPanel.language.title')"
> 71 |         >{{ $t('message.settingsPanel.language.title') }}</label>
     |         ^
  72 |       </div>
  73 |       <div>
  74 |         <select v-model="language">


5 warnings found.
5 warnings potentially fixable with the `--fix` option.```

**Comment by noroadsleft** [comment]
> Try switching from one language to another. The drop down remains in old language. You probably need to set the selected value.

Seems like the dropdown only changes when you open the side panel.

**Comment by zekth** [comment]
> > Try switching from one language to another. The drop down remains in old language. You probably need to set the selected value.
> 
> Seems like the dropdown only changes when you open the side panel.

The options are not translated as they are localized in their own language. So it's wanted behaviour. For example imagine the UI is in Japanese and all languages also. How would you find the right language? It's a pretty common pattern.

**Comment by yanfali** [comment]
> > > Try switching from one language to another. The drop down remains in old language. You probably need to set the selected value.
> > 
> > 
> > Seems like the dropdown only changes when you open the side panel.
> 
> The options are not translated as they are localized in their own language. So it's wanted behaviour. For example imagine the UI is in Japanese and all languages also. How would you find the right language? It's a pretty common pattern.

No. it's should switch to the selected option, not remain in the old language. Look at the screenshot. I switched to english but drop down still says french.

**Comment by zekth** [comment]
@yanfali fixed

**Pull request merged**
