### PR TITLE
Adjust width requirement for big enter

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

Configurator-side changes for https://github.com/qmk/qmk_firmware/pull/21470

### CODE REVIEW

**Review by tzarc — APPROVED** [review]

**Comment by yanfali** [comment]
Add a screenshot pls

**Comment by fauxpark** [comment]
There's no visual change, however now that the above PR has been merged, BAE keys *should* be rendering improperly now (which is what this is fixing). Example: `gvalchca/spaccboard:LAYOUT_bae`

Oddly the info.json requested from the Configurator has a timestamp of `2023-07-07 12:13:34 GMT` with the old key size but if I request manually it's `2023-07-07 14:11:44 GMT` and correct. Even completely restarting Firefox (also tried Chrome) doesn't change it.

**Comment by fauxpark** [comment]
Okay, whatever caching stuff was happening has expired now apparently:
image

**Comment by yanfali** [comment]
weird. I could have sworn those used to render.

**Comment by fauxpark** [comment]
They did. See the linked PR.

**Pull request merged**
