### PR TITLE
Add SA Bliss Colorway

### PR DESCRIPTION
**Pull request by mrsendyyk**
## Permission

- [x] [SA Bliss](https://github.com/qmk/qmk_configurator/pull/822#issuecomment-699541374)

### CODE REVIEW

**Comment by mrsendyyk** [comment]
Can you suggest me the change @yanfali @noroadsleft, because checks always failed.

Also sorry if it's out of topic, about #818, i still don't see GMK Nines on config.qmk.fm colorways option.

**Comment by noroadsleft** [comment]
> Also sorry if it's out of topic, about #818, i still don't see GMK Nines on config.qmk.fm colorways option. Did i miss something in my code?

Ah, the task that deploys updated versions of Configurator failed, because of one of the CI tests failed. Sometimes the CI tests can fail if the API that runs Configurator's back-end has slow response times, even when there isn't a problem with the code being tested. It's not a problem with your code, and I've restarted the deploy task.

**Review by noroadsleft — COMMENTED** [review]
:white_check_mark:  pending designer approval.

**Comment by mrsendyyk** [comment]
> 
> 
> ✅ pending designer approval.

In fact, she had given permission via email @noroadsleft.

IMG_3806

**Review by noroadsleft — APPROVED** [review]

**Review by yanfali — APPROVED** [review]

**Pull request merged**
