### PR TITLE
Create handwired_split89_default.json - default keymap for this keyboard.

### PR DESCRIPTION
**Pull request by jurassic73**
Added initial default keymap for this keyboard - handwired/split89/layout/default

### CODE REVIEW

**Review by jurassic73 — COMMENTED** [review]
Updated file name.  Looks good here.

**Comment by jurassic73** [comment]
@drashna was curious if the qmk configurator items get reviewed / added less often than the main QMK repository?  Stoked to get this added but know there's a limited number of volunteers.  :)   Thanks

**Review by noroadsleft — APPROVED** [review]

**Comment by noroadsleft** [comment]
Sorry for the slow response time. I'm the main reviewer here, but my real life has been in the way of my QMK reviews recently.

**Comment by noroadsleft** [comment]
Thanks!

**Comment by jurassic73** [comment]
> Thanks!

Totally understand on RL obligations.  Thanks for merging this in to production!  Appreciate your time!

**Pull request merged**
