### PR TITLE
French Translation

### PR DESCRIPTION
**Pull request by gab-a**
*created copy of english index.js and potato.js
*translated content to french (just translated the facts, updated stats to metric system, however some of them are very US/NA oriented, I can add some French-oriented facts if necessary)

never used Git before so hopefully I did it right 😨

### CODE REVIEW

**Comment by gab-a** [comment]
Sure I'll try to make some labels shorter while keeping it understandable for french users and I'll add some facts

**Comment by yanfali** [comment]
If you have some experience developing node, you can get the UI running locally quite easily to preview any changes in realtime

**Comment by gab-a** [comment]
thank you so much for the help, I'll try the developing node and make it work. I made some changes, I did format most of the labels to make them shorter while keeping them understandable, so I developed description titles if necessary. Added few facts, tried to catch spelling mistakes hopefully there isn't none and I think the translation is more accurate now.
tell me if you want more changes ;)

**Comment by yanfali** [comment]
I'll try and review it this evening. Thanks again for doing this. I enjoyed the new potato facts. Merci bien.

**Pull request merged**
