### PR TITLE
Fix some more keycodes

### PR DESCRIPTION
**Pull request by fauxpark**

### CODE REVIEW

**Review by yanfali — APPROVED** [review]
Do these codes need to be changed in keycode map too? Or will they just be ANY?

**Comment by fauxpark** [comment]
They weren't there to begin with.

**Comment by yanfali** [comment]
> They weren't there to begin with.

you should try and load them into the configurator. I suspect they will be set to undefined. Iirc the parser attempts to validate the codes before using them and so it will ignore codes it doesn't have.

**Comment by fauxpark** [comment]
Seems to use `ANY()` both before and after.

**Pull request merged**
