### PR TITLE
Add 'keyboard folder' button that redirects to GitHub repository

### PR DESCRIPTION
**Pull request by mateossh**
## Description

@drashna on Discord suggested this feature. 

## Screenshot

Zrzut ekranu 2022-09-28 o 15 55 43

### CODE REVIEW

**Comment by yanfali** [comment]
I think this is the right direction but I don't want to put a button for it. Let's change it to just a github icon and move it to the right of the drop down for the keyboard.

**Comment by mateossh** [comment]
Okay, it looks like this now

Zrzut ekranu 2022-09-30 220810

**Comment by yanfali** [comment]
Nice!

**Comment by yanfali** [comment]
Thank you

**Pull request merged**
