### PR TITLE
Switch upload and download icons so it makes sense

### PR DESCRIPTION
**Pull request by kleenkanteen**
Look at this:
export button

The export button has a import icon. Looks odd. I changed my layout multiple times as I've improved it and this gets me every time.

Switched the font awesome icons for the 2 icons, download and upload.

### CODE REVIEW

**Comment by skullydazed** [comment]
Maybe it's the tooltip that needs to change? Would Download/Upload or Save/Load work better instead of Export/Import?

From an iconography standpoint ISTM that the rectangle with two dot represents the user's computer, and the arrow indicates which direction the JSON will move in. From that perspective swapping them would be confusing.

**Comment by skullydazed** [comment]
Another thought- maybe instead they should swap sides of `keymap.json`. With the Full Source and Firmware download buttons being on the far right there's a certain consistency in making the "Download keymap.json" action be on the right too.

**Comment by kleenkanteen** [comment]
Hmm, I was thinking export is you are bringing it out of the site, so export the layout out, hence the arrow going up. Import is going into the site, so arrow in. So the website is the point of reference.

For the Firmware download buttons, I think it's fine as it's not deceptive at the least. But you could if you want you could, I can see why it makes more sense.

**Comment by skullydazed** [comment]
> For the Firmware download buttons, I think it's fine as it's not deceptive at the least. But you could if you want you could, I can see why it makes more sense.

To clarify- I'm not proposing changing the current firmware download buttons. Only the current import/export order.

**Comment by noroadsleft** [comment]
> From an iconography standpoint ISTM that the rectangle with two dot represents the user's computer, and the arrow indicates which direction the JSON will move in. From that perspective swapping them would be confusing.

This is exactly what it's representing. Export is Download; Import is Upload.

**Comment by noroadsleft** [comment]
I'm personally hesitant to move the buttons around or switch the icons; they've been this way since we launched this version of QMK Configurator in February of 2019, and "muscle memory" is a thing. I'd be much more receptive to changing the wording, personally.

**Comment by kleenkanteen** [comment]
Would you accept a vote from people who used it a few to couple times and are new like me?

**Comment by noroadsleft** [comment]
I understand your issue, and appreciate that you've actually gone and endeavored to fix it, but I'm not convinced this is actually an improvement. These buttons have been this way since we launched this version of Configurator two and a half years ago (and there was a publicly-accessible beta period before that), and you're the first user to complain about this in that time.

I actually find your change more confusing, because the icon swap make it look like the button functions have moved when they haven't - the left is still Export and the right is still Import.

**Comment by kleenkanteen** [comment]
I may just be the first one bothered enough to complain about it :p 

I think it'd make more sense if the icons are switched because I see the website as the point of reference.

Can I do a poll for just 1 month for new users and see what they think?

**Comment by yanfali** [comment]
Sorry but this is just bike shedding.

**Comment by kleenkanteen** [comment]
How is it bike shedding? And how is any UI improvement too small to be considered? Wheres the point where something is trivial or not?

**Comment by zvecr** [comment]
image

> I actually find your change more confusing

+1 for this. Improving usability is a fine goal, but this change isnt it.

**Comment by yanfali** [comment]
> How is it bike shedding? And how is any UI improvement too small to be considered? Wheres the point where something is trivial or not?

You've failed to convince 4 people who are collaborators that your change merits attention. I would move on, this is subjective and we as a group don't agree with your opinion.

**Pull request closed without merging**
