### PR TITLE
Update handwired_split89_default.json

### PR DESCRIPTION
**Pull request by jurassic73**
Left control key map updated to use control instead of shift.   (DOH!)

### CODE REVIEW

**Comment by jurassic73** [comment]
One last fix and my configs should be good.  Sorry for multiple fixes.

**Review by noroadsleft — COMMENTED** [review]
Have you tried flashing this to your keyboard? Comparing this to the default `keymap.c` in qmk/qmk_firmware, it looks like they don't match.

**Comment by jurassic73** [comment]
@noroadsleft - I've verified it works.  I can currently use QMK configurator to create and download working firmware that works fine minus my left control key working as a shift key. I just had to reassign left ctrl to the left ctrl key(this pull request). I performed this test last night and again just now from the main QMK page to load this firmware on my keyboard and, minus the one mismapped key, it works great.

https://config.qmk.fm/#/handwired/split89/LAYOUT

This pull request should get this in full working order by default.  Thanks for verifying. :)

**Comment by noroadsleft** [comment]
Then my guess is your default firmware on qmk/qmk_firmware won't assign the keys correctly.

**Comment by jurassic73** [comment]
it is currently though?

**Comment by noroadsleft** [comment]
I mean https://github.com/qmk/qmk_firmware/blob/45b35e6ea13d8c184d9cbd23e4bd3868e66d2933/keyboards/handwired/split89/keymaps/default/keymap.c#L23-L42 probably doesn't work correctly.

QMK Configurator keymaps need to assign their keycodes in the same order that `keymap.c` uses – this keymap doesn't, which means one or the other is wrong.

**Review by noroadsleft — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks!

**Comment by jurassic73** [comment]
@noroadsleft I appreciate you looking at this and your time!  This works now.  Forgive my ignorance if this should be written out differently.  This keymap to wiring matrix was really confusing for me.  Thanks again.

**Pull request merged**
