### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by GreekGeorge**

### CODE REVIEW

**Comment by yanfali** [comment]
@yiancar I think you will find this more accurate. Thanks @GreekGeorge

**Comment by sahalsaad** [comment]
Hi @GreekGeorge , You need to run `yarn run prettier:fix` to fix the formatting.

**Comment by GreekGeorge** [comment]
Hello @sahalsaad,
I'm not familiar with "yarn". Could you link me a walkthrough video on how to run this on a W10 system?
Thank you.

**Comment by sahalsaad** [comment]
Hi @GreekGeorge ,

1. Install yarn: https://yarnpkg.com/lang/en/docs/install/#windows-stable
2. Open terminal and `cd` to the project folder
3. Run `yarn run prettier:fix`

**Comment by yanfali** [comment]
Closing this one in favor of #556

**Pull request closed without merging**
