### PR TITLE
try to add mt3 colourway

### PR DESCRIPTION
**Pull request by alinelena**

### CODE REVIEW

**Comment by cubiq** [comment]
this is great. hope it gets merged!

--matt3o

**Comment by yanfali** [comment]
Screen Shot 2022-05-21 at 11 42 58

**Comment by noroadsleft** [comment]
I've been sick for the last few days, but I'll review this before end of tomorrow (California time).

**Comment by noroadsleft** [comment]
Slight roadblock: this branch's base was before we switched to Vite, and I don't remember how to deploy the pre-Vite Configurator. :rofl:

**Comment by tzarc** [comment]
> Slight roadblock: this branch's base was before we switched to Vite, and I don't remember how to deploy the pre-Vite Configurator. 🤣
> 
> edited to add: I may just rework this branch manually; probably would be easier than having you rebase it.

Do a merge of master into your local copy and launch with the new setup?

**Comment by yanfali** [comment]
I would consider just cherry picking too

**Comment by noroadsleft** [comment]
Superseded by #1120.

**Pull request closed without merging**
