### PR TITLE
Murcielago: change keymap according to qmk defaults

### PR DESCRIPTION
**Pull request by elagil**
Just a small change to the default keymap.
The previous RESET keycodes don't make a lot of sense if only one half is connected, as they cannot be reached in that case.

Also, make SHIFT transparent on function layers, or text cannot be selected in combination with arrows keys.

### CODE REVIEW

**Comment by elagil** [comment]
I will add further improvements and make a unified pull request later

**Comment by yanfali** [comment]
Should we close this?

**Comment by elagil** [comment]
I will update this soon, so I wouldn't close it.

**Comment by noroadsleft** [comment]
@elagil Are you planning on updating the default keymap that's on qmk_firmware? Near as I can see at a glance this keymap already matches the keymap over there and doesn't need to be updated?

**Comment by elagil** [comment]
It will be the same keymap after my PR on the qmk_firmware side passes: https://github.com/qmk/qmk_firmware/pull/9363

**Comment by elagil** [comment]
> Change the value here to `e2699773879f17e70e05dd043f2231786c6a61ad`.

Sorry, I forgot about that!

**Comment by noroadsleft** [comment]
Thanks!

**Comment by elagil** [comment]
Thanks again for merging!

**Pull request merged**
