### PR TITLE
Add deng/djam default keymap

### PR DESCRIPTION
**Pull request by myst729**
Add [deng/djam](https://config.qmk.fm/#/deng/djam/LAYOUT) default keymap

### CODE REVIEW

**Review by noroadsleft — COMMENTED** [review]
Is this the correct keymapping?

image

**Comment by myst729** [comment]
Yes, the same as https://github.com/qmk/qmk_firmware/blob/master/keyboards/deng/djam/keymaps/default/keymap.c

**Review by noroadsleft — APPROVED** [review]

**Comment by noroadsleft** [comment]
Thanks!

**Comment by myst729** [comment]
Yep, feel like a bit weird. It's the designer's request, who plays music game a lot. I'm just the tech guy and I don't play 😆

**Comment by noroadsleft** [comment]
It was more a concern because frequently my experience has been that keyboards with a layout where the keys aren't on distinct rows (like split keyboards with vertical key stagger) don't get their QMK Configurator implementations correct, so then I have to go back and fix them.

**Pull request merged**
